tasks:
- install:
- ceph:
    fs: xfs
    log-whitelist: ['Failed to load ceph-mgr modules: rook']
    conf:
      mds:
        debug mds: 20
        debug ms: 1
      client:
        debug client: 20
        debug ms: 1
        fuse default permissions: false
        fuse set user groups: true
- ceph-fuse:
- workunit:
    clients:
      all:
        - suites/pjd.sh
