overrides:
  ceph:
    conf:
      global:
        ms die on skipped message: false
tasks:
- install:
- ceph:
    log-whitelist: ['Failed to load ceph-mgr modules: rook']
- kclient:
- workunit:
    clients:
      all:
        - direct_io
