tasks:
- install:
- ceph:
    fs: ext4
    log-whitelist:
    - but it is still running
    - overall HEALTH_
    - \(POOL_APP_NOT_ENABLED\)
    - Failed to load ceph-mgr modules:rook
- ceph-fuse:
- workunit:
    clients:
      all:
        - rados/load-gen-mix.sh
