tasks:
- install:
- ceph:
    log-whitelist:
    - but it is still running
    - overall HEALTH_
    - \(OSDMAP_FLAGS\)
    - \(PG_
    - \(OSD_
    - \(OBJECT_
    - \(POOL_APP_NOT_ENABLED\)
    - Failed to load ceph-mgr modules:rook
- ceph-fuse:
- workunit:
    clients:
      client.0:
        - rados/test_python.sh
