tasks:
- install:
- ceph:
    log-whitelist: ['Failed to load ceph-mgr modules: rook']
- ceph-fuse:
- workunit:
    clients:
      client.0:
        - rbd/test_librbd_python.sh
    env:
      RBD_FEATURES: "1"
