tasks:
- install:
- ceph:
    fs: ext4
    log-whitelist: ['Failed to load ceph-mgr modules: rook']
- rgw: [client.0]
- swift:
    client.0:
      force-branch: ceph-nautilus
      rgw_server: client.0
